### ISSUE TITLE
load_advisers import with June 2015 dataset didn't work with existing data

### ISSUE THREAD

**Issue by ashb** [ministryofjustice/laa-legal-adviser-api#20]
When we tried to import "150618 Find an Adviser MASTER v1.xlsx" we got an constraint error.

I've lost the error now but it was something like "account_number 0A063U is not unique"

(Ask Ash or Alex for a copy of this file.)

**Comment by sldblog** [comment]
Closing as this issue is 3 years old and the method for importing advisers has changed since.
