### ISSUE TITLE
Import fails with "total" sheet not found

### ISSUE THREAD

**Issue by ashb** [ministryofjustice/laa-legal-adviser-api#22]
At the end running `manage.py load_advisers "150618 Find an Adviser MASTER v1.xlsx" we get this error in red

```
CommandError: Failed opening Excel spreadsheet: 'total'
done
Exception AttributeError: "'NoneType' object has no attribute 'destroy_geom'" in  ignored
```

**Comment by sldblog** [comment]
Closing this issue as it is 3 years old and the `load_advisers` task does not exist anymore.
